/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/healthz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness check */
    get: operations['healthz']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/openapi.yaml': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** This specification */
    get: operations['getOpenAPI']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Log in with a local account
     * @description Starts a session. Failed attempts are throttled per login and per client IP with
     *     exponential backoff (429 with `Retry-After`).
     */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Rotate the refresh session and issue a new access token
     * @description Uses the `tt_refresh` cookie. The old refresh token becomes invalid.
     */
    post: operations['refreshSession']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * End the session
     * @description Revokes the refresh session and clears the cookies. Always succeeds.
     */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The current account */
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/buildings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List buildings */
    get: operations['listBuildings']
    put?: never
    /** Create a building */
    post: operations['createBuilding']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/buildings/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    /** Get a building */
    get: operations['getBuilding']
    /** Replace a building */
    put: operations['updateBuilding']
    post?: never
    /**
     * Delete a building
     * @description Fails with 409 `in_use` while rooms reference it.
     */
    delete: operations['deleteBuilding']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/room-types': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List room types */
    get: operations['listRoomTypes']
    put?: never
    /** Create a room type */
    post: operations['createRoomType']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/room-types/{code}': {
    parameters: {
      query?: never
      header?: never
      path: {
        code: components['schemas']['Code']
      }
      cookie?: never
    }
    /** Get a room type */
    get: operations['getRoomType']
    /** Rename a room type (the code is immutable) */
    put: operations['updateRoomType']
    post?: never
    /**
     * Delete a room type
     * @description Fails with 409 `in_use` while rooms or curriculum items reference it.
     */
    delete: operations['deleteRoomType']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/rooms': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List rooms */
    get: operations['listRooms']
    put?: never
    /** Create a room */
    post: operations['createRoom']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/rooms/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    /** Get a room */
    get: operations['getRoom']
    /** Replace a room */
    put: operations['updateRoom']
    post?: never
    /**
     * Delete a room
     * @description Fails with 409 `in_use` while schedule assignments use it.
     */
    delete: operations['deleteRoom']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/rooms/{id}/availability': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    /** Availability exceptions of a room */
    get: operations['getRoomAvailability']
    /** Replace the availability exceptions of a room */
    put: operations['putRoomAvailability']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List groups */
    get: operations['listGroups']
    put?: never
    /** Create a group */
    post: operations['createGroup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/groups/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    /** Get a group */
    get: operations['getGroup']
    /** Replace a group */
    put: operations['updateGroup']
    post?: never
    /**
     * Delete a group
     * @description Deletes its subgroups too; fails with 409 `in_use` while curriculum items reference it.
     */
    delete: operations['deleteGroup']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/groups/{id}/subgroups': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    /** List the subgroups of a group */
    get: operations['listSubgroups']
    put?: never
    /** Create a subgroup */
    post: operations['createSubgroup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/groups/{id}/subgroups/{subgroup_id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
        subgroup_id: components['schemas']['ID']
      }
      cookie?: never
    }
    /** Get a subgroup */
    get: operations['getSubgroup']
    /** Replace a subgroup */
    put: operations['updateSubgroup']
    post?: never
    /** Delete a subgroup */
    delete: operations['deleteSubgroup']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/teachers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List teachers */
    get: operations['listTeachers']
    put?: never
    /** Create a teacher */
    post: operations['createTeacher']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/teachers/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    /** Get a teacher */
    get: operations['getTeacher']
    /** Replace a teacher */
    put: operations['updateTeacher']
    post?: never
    /**
     * Delete a teacher
     * @description Fails with 409 `in_use` while curriculum items reference the teacher.
     */
    delete: operations['deleteTeacher']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/teachers/{id}/availability': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    /** Availability exceptions of a teacher */
    get: operations['getTeacherAvailability']
    /** Replace the availability exceptions of a teacher */
    put: operations['putTeacherAvailability']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/disciplines': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List disciplines */
    get: operations['listDisciplines']
    put?: never
    /** Create a discipline */
    post: operations['createDiscipline']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/disciplines/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    /** Get a discipline */
    get: operations['getDiscipline']
    /** Rename a discipline */
    put: operations['updateDiscipline']
    post?: never
    /**
     * Delete a discipline
     * @description Fails with 409 `in_use` while curriculum items reference it.
     */
    delete: operations['deleteDiscipline']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/time-grid': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The week shape */
    get: operations['getTimeGrid']
    /** Set the week shape */
    put: operations['putTimeGrid']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/periods': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List periods (pairs) with their times */
    get: operations['listPeriods']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/periods/{number}': {
    parameters: {
      query?: never
      header?: never
      path: {
        number: number
      }
      cookie?: never
    }
    /** Get a period */
    get: operations['getPeriod']
    /** Create or replace a period */
    put: operations['putPeriod']
    post?: never
    /** Delete a period */
    delete: operations['deletePeriod']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/curriculum-items': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List curriculum items with their audience and lessons */
    get: operations['listCurriculumItems']
    put?: never
    /**
     * Create a curriculum item
     * @description Creates the item, its audience and its lessons in one transaction: `weekly_count`
     *     weekly lessons followed by `biweekly_count` biweekly ones, numbered `seq` 1..N.
     */
    post: operations['createCurriculumItem']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/curriculum-items/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    /** Get a curriculum item */
    get: operations['getCurriculumItem']
    /**
     * Replace a curriculum item
     * @description Replaces the item and its audience. When `weekly_count` or `biweekly_count` change, the
     *     lessons are regenerated in the same transaction; the old lessons' schedule assignments
     *     are deleted with them (ON DELETE CASCADE). A change that makes existing assignments
     *     collide (teacher or audience double booking) fails with 409 `schedule_conflict`.
     */
    put: operations['updateCurriculumItem']
    post?: never
    /**
     * Delete a curriculum item
     * @description Deletes its audience, lessons and their schedule assignments too.
     */
    delete: operations['deleteCurriculumItem']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Format: int64 */
    ID: number
    Name: string
    Code: string
    /** @example 08:30 */
    Clock: string
    Error: {
      error: {
        /** @example not_found */
        code: string
        message: string
      }
    }
    /** @enum {string} */
    Role: 'student' | 'teacher' | 'admin' | 'ai_agent'
    User: {
      id: components['schemas']['ID']
      login: string
      role: components['schemas']['Role']
      display_name: string
      /** Format: int64 */
      teacher_id: number | null
      /** Format: int64 */
      group_id: number | null
      /** Format: date-time */
      created_at: string
    }
    Session: {
      user: components['schemas']['User']
      /** @description HS256 JWT, also set as the tt_access cookie. */
      access_token: string
      /** Format: date-time */
      expires_at: string
    }
    Building: {
      id: components['schemas']['ID']
      name: components['schemas']['Name']
      address: string
    }
    BuildingInput: {
      name: components['schemas']['Name']
      /** @default  */
      address: string
    }
    RoomType: {
      code: components['schemas']['Code']
      name: components['schemas']['Name']
    }
    Room: {
      id: components['schemas']['ID']
      building_id: components['schemas']['ID']
      name: components['schemas']['Name']
      room_type: components['schemas']['Code']
      capacity: number
    }
    RoomInput: {
      building_id: components['schemas']['ID']
      name: components['schemas']['Name']
      room_type: components['schemas']['Code']
      capacity: number
    }
    Group: {
      id: components['schemas']['ID']
      name: components['schemas']['Name']
      course: number
      size: number
    }
    GroupInput: {
      name: components['schemas']['Name']
      /** @default 1 */
      course: number
      size: number
    }
    Subgroup: {
      id: components['schemas']['ID']
      group_id: components['schemas']['ID']
      /** @description Name of one way to split the group, e.g. "lab". */
      division: string
      part: number
      size: number
    }
    SubgroupInput: {
      division: string
      part: number
      size: number
    }
    Teacher: {
      id: components['schemas']['ID']
      full_name: components['schemas']['Name']
      short_name: components['schemas']['Name']
    }
    TeacherInput: {
      full_name: components['schemas']['Name']
      short_name: components['schemas']['Name']
    }
    Discipline: {
      id: components['schemas']['ID']
      name: components['schemas']['Name']
    }
    DisciplineInput: {
      name: components['schemas']['Name']
    }
    /** @enum {string} */
    Parity: 'every' | 'odd' | 'even'
    AvailabilityEntry: {
      /** @description 0 = Monday. */
      day: number
      period: number
      /** @default every */
      parity: components['schemas']['Parity']
      /** @enum {string} */
      status: 'unavailable' | 'undesired' | 'preferred'
    }
    /** @description Exceptions per slot; a slot without an entry is available with no preference. */
    Availability: {
      entries: components['schemas']['AvailabilityEntry'][]
    }
    TimeGrid: {
      days: number
      periods_per_day: number
    }
    Period: {
      number: number
      starts_at: components['schemas']['Clock']
      ends_at: components['schemas']['Clock']
    }
    /** @description A whole group (`division` empty, `part` 0) or part `part` of the group's `division`. */
    AudienceMember: {
      group_id: components['schemas']['ID']
      /** @default  */
      division: string
      /** @default 0 */
      part: number
    }
    Lesson: {
      id: components['schemas']['ID']
      seq: number
      biweekly: boolean
    }
    /** @enum {string} */
    LessonKind: 'lecture' | 'seminar' | 'lab'
    CurriculumItemInput: {
      discipline_id: components['schemas']['ID']
      kind: components['schemas']['LessonKind']
      teacher_id: components['schemas']['ID']
      room_type: components['schemas']['Code']
      /** @default 0 */
      weekly_count: number
      /**
       * @description weekly_count + biweekly_count must be positive.
       * @default 0
       */
      biweekly_count: number
      audience: components['schemas']['AudienceMember'][]
    }
    CurriculumItem: {
      id: components['schemas']['ID']
      discipline_id: components['schemas']['ID']
      kind: components['schemas']['LessonKind']
      teacher_id: components['schemas']['ID']
      room_type: components['schemas']['Code']
      weekly_count: number
      biweekly_count: number
      audience: components['schemas']['AudienceMember'][]
      lessons: components['schemas']['Lesson'][]
    }
  }
  responses: {
    /** @description The building. */
    Building: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Building']
      }
    }
    /** @description The room type. */
    RoomType: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['RoomType']
      }
    }
    /** @description The room. */
    Room: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Room']
      }
    }
    /** @description The group. */
    Group: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Group']
      }
    }
    /** @description The subgroup. */
    Subgroup: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Subgroup']
      }
    }
    /** @description The teacher. */
    Teacher: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Teacher']
      }
    }
    /** @description The discipline. */
    Discipline: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Discipline']
      }
    }
    /** @description The availability exceptions. */
    Availability: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Availability']
      }
    }
    /** @description The time grid. */
    TimeGrid: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['TimeGrid']
      }
    }
    /** @description The period. */
    Period: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Period']
      }
    }
    /** @description The curriculum item with its audience and lessons. */
    CurriculumItem: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['CurriculumItem']
      }
    }
    /** @description Malformed request (`invalid_request`). */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description No valid session (`unauthorized`). */
    Unauthorized: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The role may not do this (`forbidden`). */
    Forbidden: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The record does not exist (`not_found`). */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Unique key taken (`already_exists`), record still referenced (`in_use`) or schedule collision (`schedule_conflict`). */
    Conflict: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Invalid field values (`validation_failed`), missing referenced record (`invalid_reference`) or database constraint (`constraint_violation`). */
    Unprocessable: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The server runs without a database (`no_database`). */
    NoDatabase: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
  }
  parameters: {
    ID: components['schemas']['ID']
  }
  requestBodies: {
    BuildingInput: {
      content: {
        'application/json': components['schemas']['BuildingInput']
      }
    }
    RoomInput: {
      content: {
        'application/json': components['schemas']['RoomInput']
      }
    }
    GroupInput: {
      content: {
        'application/json': components['schemas']['GroupInput']
      }
    }
    SubgroupInput: {
      content: {
        'application/json': components['schemas']['SubgroupInput']
      }
    }
    TeacherInput: {
      content: {
        'application/json': components['schemas']['TeacherInput']
      }
    }
    DisciplineInput: {
      content: {
        'application/json': components['schemas']['DisciplineInput']
      }
    }
    Availability: {
      content: {
        'application/json': components['schemas']['Availability']
      }
    }
    CurriculumItemInput: {
      content: {
        'application/json': components['schemas']['CurriculumItemInput']
      }
    }
  }
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  healthz: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The server is up. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @constant */
            status: 'ok'
          }
        }
      }
    }
  }
  getOpenAPI: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OpenAPI document. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/yaml': string
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description Case-insensitive. */
          login: string
          password: string
        }
      }
    }
    responses: {
      /** @description Logged in; `tt_access` and `tt_refresh` cookies are set. */
      200: {
        headers: {
          'Set-Cookie'?: string
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Session']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      /** @description The account is disabled (`account_disabled`). */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Too many failed attempts (`too_many_attempts`). */
      429: {
        headers: {
          /** @description Seconds to wait. */
          'Retry-After'?: number
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      503: components['responses']['NoDatabase']
    }
  }
  refreshSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description New tokens; cookies are replaced. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Session']
        }
      }
      401: components['responses']['Unauthorized']
      503: components['responses']['NoDatabase']
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logged out. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The authenticated user. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      401: components['responses']['Unauthorized']
      503: components['responses']['NoDatabase']
    }
  }
  listBuildings: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Buildings ordered by name. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Building'][]
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  createBuilding: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['BuildingInput']
    responses: {
      201: components['responses']['Building']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  getBuilding: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['Building']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  updateBuilding: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['BuildingInput']
    responses: {
      200: components['responses']['Building']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  deleteBuilding: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  listRoomTypes: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Room types ordered by code. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoomType'][]
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  createRoomType: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RoomType']
      }
    }
    responses: {
      201: components['responses']['RoomType']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  getRoomType: {
    parameters: {
      query?: never
      header?: never
      path: {
        code: components['schemas']['Code']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['RoomType']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  updateRoomType: {
    parameters: {
      query?: never
      header?: never
      path: {
        code: components['schemas']['Code']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          name: components['schemas']['Name']
        }
      }
    }
    responses: {
      200: components['responses']['RoomType']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      422: components['responses']['Unprocessable']
    }
  }
  deleteRoomType: {
    parameters: {
      query?: never
      header?: never
      path: {
        code: components['schemas']['Code']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  listRooms: {
    parameters: {
      query?: {
        building_id?: components['schemas']['ID']
        room_type?: components['schemas']['Code']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Rooms ordered by building and name. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Room'][]
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  createRoom: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['RoomInput']
    responses: {
      201: components['responses']['Room']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  getRoom: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['Room']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  updateRoom: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['RoomInput']
    responses: {
      200: components['responses']['Room']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  deleteRoom: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  getRoomAvailability: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['Availability']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  putRoomAvailability: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['Availability']
    responses: {
      200: components['responses']['Availability']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      422: components['responses']['Unprocessable']
    }
  }
  listGroups: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Groups ordered by name. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Group'][]
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  createGroup: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['GroupInput']
    responses: {
      201: components['responses']['Group']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  getGroup: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['Group']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  updateGroup: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['GroupInput']
    responses: {
      200: components['responses']['Group']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  deleteGroup: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  listSubgroups: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Subgroups ordered by division and part. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Subgroup'][]
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  createSubgroup: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['SubgroupInput']
    responses: {
      201: components['responses']['Subgroup']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  getSubgroup: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
        subgroup_id: components['schemas']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['Subgroup']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  updateSubgroup: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
        subgroup_id: components['schemas']['ID']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['SubgroupInput']
    responses: {
      200: components['responses']['Subgroup']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  deleteSubgroup: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
        subgroup_id: components['schemas']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  listTeachers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Teachers ordered by full name. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Teacher'][]
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  createTeacher: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['TeacherInput']
    responses: {
      201: components['responses']['Teacher']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      422: components['responses']['Unprocessable']
    }
  }
  getTeacher: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['Teacher']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  updateTeacher: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['TeacherInput']
    responses: {
      200: components['responses']['Teacher']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      422: components['responses']['Unprocessable']
    }
  }
  deleteTeacher: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  getTeacherAvailability: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['Availability']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  putTeacherAvailability: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['Availability']
    responses: {
      200: components['responses']['Availability']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      422: components['responses']['Unprocessable']
    }
  }
  listDisciplines: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Disciplines ordered by name. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Discipline'][]
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  createDiscipline: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['DisciplineInput']
    responses: {
      201: components['responses']['Discipline']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  getDiscipline: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['Discipline']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  updateDiscipline: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['DisciplineInput']
    responses: {
      200: components['responses']['Discipline']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  deleteDiscipline: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  getTimeGrid: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['TimeGrid']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  putTimeGrid: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TimeGrid']
      }
    }
    responses: {
      200: components['responses']['TimeGrid']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      422: components['responses']['Unprocessable']
    }
  }
  listPeriods: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Periods ordered by number. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Period'][]
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  getPeriod: {
    parameters: {
      query?: never
      header?: never
      path: {
        number: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['Period']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  putPeriod: {
    parameters: {
      query?: never
      header?: never
      path: {
        number: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          starts_at: components['schemas']['Clock']
          ends_at: components['schemas']['Clock']
        }
      }
    }
    responses: {
      200: components['responses']['Period']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      422: components['responses']['Unprocessable']
    }
  }
  deletePeriod: {
    parameters: {
      query?: never
      header?: never
      path: {
        number: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
  listCurriculumItems: {
    parameters: {
      query?: {
        teacher_id?: components['schemas']['ID']
        discipline_id?: components['schemas']['ID']
        /** @description Items whose audience includes the group. */
        group_id?: components['schemas']['ID']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Curriculum items ordered by id. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CurriculumItem'][]
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
    }
  }
  createCurriculumItem: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: components['requestBodies']['CurriculumItemInput']
    responses: {
      201: components['responses']['CurriculumItem']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      422: components['responses']['Unprocessable']
    }
  }
  getCurriculumItem: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: components['responses']['CurriculumItem']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
    }
  }
  updateCurriculumItem: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody: components['requestBodies']['CurriculumItemInput']
    responses: {
      200: components['responses']['CurriculumItem']
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
      422: components['responses']['Unprocessable']
    }
  }
  deleteCurriculumItem: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['ID']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
    }
  }
}
