// @vitest-environment node
//
// Fails when src/api/schema.ts (generated by `npm run gen:api`) is out of date with
// backend/api/openapi.yaml. Fix: `cd frontend && npm run gen:api` and commit the result.
import { readFile } from 'node:fs/promises'
import openapiTS, { astToString, COMMENT_HEADER } from 'openapi-typescript'
import { format, resolveConfig } from 'prettier'
import { expect, it } from 'vitest'

const specURL = new URL('../../backend/api/openapi.yaml', import.meta.url)
const schemaURL = new URL('../src/api/schema.ts', import.meta.url)

it('src/api/schema.ts matches backend/api/openapi.yaml (run `npm run gen:api`)', async () => {
  const ast = await openapiTS(specURL)
  const config = await resolveConfig(schemaURL)
  const expected = await format(COMMENT_HEADER + astToString(ast), {
    ...config,
    parser: 'typescript',
  })
  const actual = await readFile(schemaURL, 'utf8')
  expect(actual === expected, 'src/api/schema.ts is stale: run `npm run gen:api`').toBe(true)
}, 30_000)
