// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAudit = `-- name: InsertAudit :one
INSERT INTO audit_log (actor_type, actor_id, via_assistant, entity, entity_id, before, after, diff, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, at, actor_type, actor_id, via_assistant, entity, entity_id, before, after, diff, reason
`

type InsertAuditParams struct {
	ActorType    ActorType
	ActorID      string
	ViaAssistant bool
	Entity       string
	EntityID     string
	Before       []byte
	After        []byte
	Diff         []byte
	Reason       string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAudit,
		arg.ActorType,
		arg.ActorID,
		arg.ViaAssistant,
		arg.Entity,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.Diff,
		arg.Reason,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.ActorType,
		&i.ActorID,
		&i.ViaAssistant,
		&i.Entity,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.Diff,
		&i.Reason,
	)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, actor_type, actor_id, via_assistant, entity, entity_id, before, after, diff, reason FROM audit_log
WHERE ($3::text IS NULL OR entity = $3)
  AND ($4::text IS NULL OR entity_id = $4)
ORDER BY at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAuditParams struct {
	Limit    int32
	Offset   int32
	Entity   pgtype.Text
	EntityID pgtype.Text
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.Limit,
		arg.Offset,
		arg.Entity,
		arg.EntityID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorType,
			&i.ActorID,
			&i.ViaAssistant,
			&i.Entity,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.Diff,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
