// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crud.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoomType = `-- name: CreateRoomType :one
INSERT INTO room_types (code, name) VALUES ($1, $2) RETURNING code, name
`

type CreateRoomTypeParams struct {
	Code string
	Name string
}

func (q *Queries) CreateRoomType(ctx context.Context, arg CreateRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRow(ctx, createRoomType, arg.Code, arg.Name)
	var i RoomType
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}

const deletePeriod = `-- name: DeletePeriod :execrows
DELETE FROM periods WHERE number = $1
`

func (q *Queries) DeletePeriod(ctx context.Context, number int16) (int64, error) {
	result, err := q.db.Exec(ctx, deletePeriod, number)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRoomType = `-- name: DeleteRoomType :execrows
DELETE FROM room_types WHERE code = $1
`

func (q *Queries) DeleteRoomType(ctx context.Context, code string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoomType, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSubgroupOf = `-- name: DeleteSubgroupOf :execrows
DELETE FROM subgroups WHERE group_id = $1 AND id = $2
`

type DeleteSubgroupOfParams struct {
	GroupID int64
	ID      int64
}

func (q *Queries) DeleteSubgroupOf(ctx context.Context, arg DeleteSubgroupOfParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubgroupOf, arg.GroupID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPeriod = `-- name: GetPeriod :one
SELECT number, starts_at, ends_at FROM periods WHERE number = $1
`

func (q *Queries) GetPeriod(ctx context.Context, number int16) (Period, error) {
	row := q.db.QueryRow(ctx, getPeriod, number)
	var i Period
	err := row.Scan(&i.Number, &i.StartsAt, &i.EndsAt)
	return i, err
}

const getRoomType = `-- name: GetRoomType :one

SELECT code, name FROM room_types WHERE code = $1
`

// Queries used by the reference-data REST API (single-row access for CRUD).
func (q *Queries) GetRoomType(ctx context.Context, code string) (RoomType, error) {
	row := q.db.QueryRow(ctx, getRoomType, code)
	var i RoomType
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}

const getSubgroupOf = `-- name: GetSubgroupOf :one
SELECT id, group_id, division, part, size FROM subgroups WHERE group_id = $1 AND id = $2
`

type GetSubgroupOfParams struct {
	GroupID int64
	ID      int64
}

func (q *Queries) GetSubgroupOf(ctx context.Context, arg GetSubgroupOfParams) (Subgroup, error) {
	row := q.db.QueryRow(ctx, getSubgroupOf, arg.GroupID, arg.ID)
	var i Subgroup
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Division,
		&i.Part,
		&i.Size,
	)
	return i, err
}

const listCurriculumAudienceOf = `-- name: ListCurriculumAudienceOf :many
SELECT curriculum_item_id, group_id, division, part FROM curriculum_audience WHERE curriculum_item_id = $1 ORDER BY group_id, division, part
`

func (q *Queries) ListCurriculumAudienceOf(ctx context.Context, curriculumItemID int64) ([]CurriculumAudience, error) {
	rows, err := q.db.Query(ctx, listCurriculumAudienceOf, curriculumItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurriculumAudience{}
	for rows.Next() {
		var i CurriculumAudience
		if err := rows.Scan(
			&i.CurriculumItemID,
			&i.GroupID,
			&i.Division,
			&i.Part,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurriculumItemsFiltered = `-- name: ListCurriculumItemsFiltered :many
SELECT id, discipline_id, kind, teacher_id, room_type, weekly_count, biweekly_count FROM curriculum_items ci
WHERE ($1::bigint IS NULL OR ci.teacher_id = $1)
  AND ($2::bigint IS NULL OR ci.discipline_id = $2)
  AND ($3::bigint IS NULL OR EXISTS (
        SELECT 1 FROM curriculum_audience ca
        WHERE ca.curriculum_item_id = ci.id AND ca.group_id = $3))
ORDER BY ci.id
`

type ListCurriculumItemsFilteredParams struct {
	TeacherID    pgtype.Int8
	DisciplineID pgtype.Int8
	GroupID      pgtype.Int8
}

func (q *Queries) ListCurriculumItemsFiltered(ctx context.Context, arg ListCurriculumItemsFilteredParams) ([]CurriculumItem, error) {
	rows, err := q.db.Query(ctx, listCurriculumItemsFiltered, arg.TeacherID, arg.DisciplineID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurriculumItem{}
	for rows.Next() {
		var i CurriculumItem
		if err := rows.Scan(
			&i.ID,
			&i.DisciplineID,
			&i.Kind,
			&i.TeacherID,
			&i.RoomType,
			&i.WeeklyCount,
			&i.BiweeklyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsOf = `-- name: ListLessonsOf :many
SELECT id, curriculum_item_id, seq, biweekly FROM lessons WHERE curriculum_item_id = $1 ORDER BY seq
`

func (q *Queries) ListLessonsOf(ctx context.Context, curriculumItemID int64) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsOf, curriculumItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.CurriculumItemID,
			&i.Seq,
			&i.Biweekly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomAvailabilityOf = `-- name: ListRoomAvailabilityOf :many
SELECT room_id, day, period, parity, status FROM room_availability WHERE room_id = $1 ORDER BY day, period, parity
`

func (q *Queries) ListRoomAvailabilityOf(ctx context.Context, roomID int64) ([]RoomAvailability, error) {
	rows, err := q.db.Query(ctx, listRoomAvailabilityOf, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomAvailability{}
	for rows.Next() {
		var i RoomAvailability
		if err := rows.Scan(
			&i.RoomID,
			&i.Day,
			&i.Period,
			&i.Parity,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsFiltered = `-- name: ListRoomsFiltered :many
SELECT id, building_id, name, room_type, capacity FROM rooms
WHERE ($1::bigint IS NULL OR building_id = $1)
  AND ($2::text IS NULL OR room_type = $2)
ORDER BY building_id, name
`

type ListRoomsFilteredParams struct {
	BuildingID pgtype.Int8
	RoomType   pgtype.Text
}

func (q *Queries) ListRoomsFiltered(ctx context.Context, arg ListRoomsFilteredParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsFiltered, arg.BuildingID, arg.RoomType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.BuildingID,
			&i.Name,
			&i.RoomType,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubgroupsOf = `-- name: ListSubgroupsOf :many
SELECT id, group_id, division, part, size FROM subgroups WHERE group_id = $1 ORDER BY division, part
`

func (q *Queries) ListSubgroupsOf(ctx context.Context, groupID int64) ([]Subgroup, error) {
	rows, err := q.db.Query(ctx, listSubgroupsOf, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subgroup{}
	for rows.Next() {
		var i Subgroup
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Division,
			&i.Part,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherAvailabilityOf = `-- name: ListTeacherAvailabilityOf :many
SELECT teacher_id, day, period, parity, status FROM teacher_availability WHERE teacher_id = $1 ORDER BY day, period, parity
`

func (q *Queries) ListTeacherAvailabilityOf(ctx context.Context, teacherID int64) ([]TeacherAvailability, error) {
	rows, err := q.db.Query(ctx, listTeacherAvailabilityOf, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherAvailability{}
	for rows.Next() {
		var i TeacherAvailability
		if err := rows.Scan(
			&i.TeacherID,
			&i.Day,
			&i.Period,
			&i.Parity,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomType = `-- name: UpdateRoomType :one
UPDATE room_types SET name = $2 WHERE code = $1 RETURNING code, name
`

type UpdateRoomTypeParams struct {
	Code string
	Name string
}

func (q *Queries) UpdateRoomType(ctx context.Context, arg UpdateRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRow(ctx, updateRoomType, arg.Code, arg.Name)
	var i RoomType
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}

const updateSubgroupOf = `-- name: UpdateSubgroupOf :one
UPDATE subgroups SET division = $3, part = $4, size = $5 WHERE group_id = $1 AND id = $2 RETURNING id, group_id, division, part, size
`

type UpdateSubgroupOfParams struct {
	GroupID  int64
	ID       int64
	Division string
	Part     int16
	Size     int32
}

func (q *Queries) UpdateSubgroupOf(ctx context.Context, arg UpdateSubgroupOfParams) (Subgroup, error) {
	row := q.db.QueryRow(ctx, updateSubgroupOf,
		arg.GroupID,
		arg.ID,
		arg.Division,
		arg.Part,
		arg.Size,
	)
	var i Subgroup
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Division,
		&i.Part,
		&i.Size,
	)
	return i, err
}
