// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: curriculum.sql

package db

import (
	"context"
)

const addCurriculumAudience = `-- name: AddCurriculumAudience :exec
INSERT INTO curriculum_audience (curriculum_item_id, group_id, division, part) VALUES ($1, $2, $3, $4)
`

type AddCurriculumAudienceParams struct {
	CurriculumItemID int64
	GroupID          int64
	Division         string
	Part             int16
}

func (q *Queries) AddCurriculumAudience(ctx context.Context, arg AddCurriculumAudienceParams) error {
	_, err := q.db.Exec(ctx, addCurriculumAudience,
		arg.CurriculumItemID,
		arg.GroupID,
		arg.Division,
		arg.Part,
	)
	return err
}

const clearCurriculumAudience = `-- name: ClearCurriculumAudience :exec
DELETE FROM curriculum_audience WHERE curriculum_item_id = $1
`

func (q *Queries) ClearCurriculumAudience(ctx context.Context, curriculumItemID int64) error {
	_, err := q.db.Exec(ctx, clearCurriculumAudience, curriculumItemID)
	return err
}

const createCurriculumItem = `-- name: CreateCurriculumItem :one
INSERT INTO curriculum_items (discipline_id, kind, teacher_id, room_type, weekly_count, biweekly_count)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, discipline_id, kind, teacher_id, room_type, weekly_count, biweekly_count
`

type CreateCurriculumItemParams struct {
	DisciplineID  int64
	Kind          LessonKind
	TeacherID     int64
	RoomType      string
	WeeklyCount   int16
	BiweeklyCount int16
}

func (q *Queries) CreateCurriculumItem(ctx context.Context, arg CreateCurriculumItemParams) (CurriculumItem, error) {
	row := q.db.QueryRow(ctx, createCurriculumItem,
		arg.DisciplineID,
		arg.Kind,
		arg.TeacherID,
		arg.RoomType,
		arg.WeeklyCount,
		arg.BiweeklyCount,
	)
	var i CurriculumItem
	err := row.Scan(
		&i.ID,
		&i.DisciplineID,
		&i.Kind,
		&i.TeacherID,
		&i.RoomType,
		&i.WeeklyCount,
		&i.BiweeklyCount,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (curriculum_item_id, seq, biweekly) VALUES ($1, $2, $3) RETURNING id, curriculum_item_id, seq, biweekly
`

type CreateLessonParams struct {
	CurriculumItemID int64
	Seq              int16
	Biweekly         bool
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson, arg.CurriculumItemID, arg.Seq, arg.Biweekly)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CurriculumItemID,
		&i.Seq,
		&i.Biweekly,
	)
	return i, err
}

const deleteCurriculumItem = `-- name: DeleteCurriculumItem :execrows
DELETE FROM curriculum_items WHERE id = $1
`

func (q *Queries) DeleteCurriculumItem(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCurriculumItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLessonsOfItem = `-- name: DeleteLessonsOfItem :exec
DELETE FROM lessons WHERE curriculum_item_id = $1
`

func (q *Queries) DeleteLessonsOfItem(ctx context.Context, curriculumItemID int64) error {
	_, err := q.db.Exec(ctx, deleteLessonsOfItem, curriculumItemID)
	return err
}

const getCurriculumItem = `-- name: GetCurriculumItem :one
SELECT id, discipline_id, kind, teacher_id, room_type, weekly_count, biweekly_count FROM curriculum_items WHERE id = $1
`

func (q *Queries) GetCurriculumItem(ctx context.Context, id int64) (CurriculumItem, error) {
	row := q.db.QueryRow(ctx, getCurriculumItem, id)
	var i CurriculumItem
	err := row.Scan(
		&i.ID,
		&i.DisciplineID,
		&i.Kind,
		&i.TeacherID,
		&i.RoomType,
		&i.WeeklyCount,
		&i.BiweeklyCount,
	)
	return i, err
}

const listCurriculumAudience = `-- name: ListCurriculumAudience :many
SELECT curriculum_item_id, group_id, division, part FROM curriculum_audience ORDER BY curriculum_item_id, group_id, division, part
`

func (q *Queries) ListCurriculumAudience(ctx context.Context) ([]CurriculumAudience, error) {
	rows, err := q.db.Query(ctx, listCurriculumAudience)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurriculumAudience{}
	for rows.Next() {
		var i CurriculumAudience
		if err := rows.Scan(
			&i.CurriculumItemID,
			&i.GroupID,
			&i.Division,
			&i.Part,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurriculumItems = `-- name: ListCurriculumItems :many
SELECT id, discipline_id, kind, teacher_id, room_type, weekly_count, biweekly_count FROM curriculum_items ORDER BY id
`

func (q *Queries) ListCurriculumItems(ctx context.Context) ([]CurriculumItem, error) {
	rows, err := q.db.Query(ctx, listCurriculumItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurriculumItem{}
	for rows.Next() {
		var i CurriculumItem
		if err := rows.Scan(
			&i.ID,
			&i.DisciplineID,
			&i.Kind,
			&i.TeacherID,
			&i.RoomType,
			&i.WeeklyCount,
			&i.BiweeklyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessons = `-- name: ListLessons :many
SELECT id, curriculum_item_id, seq, biweekly FROM lessons ORDER BY curriculum_item_id, seq
`

func (q *Queries) ListLessons(ctx context.Context) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.CurriculumItemID,
			&i.Seq,
			&i.Biweekly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurriculumItem = `-- name: UpdateCurriculumItem :one
UPDATE curriculum_items
SET discipline_id = $2, kind = $3, teacher_id = $4, room_type = $5, weekly_count = $6, biweekly_count = $7
WHERE id = $1
RETURNING id, discipline_id, kind, teacher_id, room_type, weekly_count, biweekly_count
`

type UpdateCurriculumItemParams struct {
	ID            int64
	DisciplineID  int64
	Kind          LessonKind
	TeacherID     int64
	RoomType      string
	WeeklyCount   int16
	BiweeklyCount int16
}

func (q *Queries) UpdateCurriculumItem(ctx context.Context, arg UpdateCurriculumItemParams) (CurriculumItem, error) {
	row := q.db.QueryRow(ctx, updateCurriculumItem,
		arg.ID,
		arg.DisciplineID,
		arg.Kind,
		arg.TeacherID,
		arg.RoomType,
		arg.WeeklyCount,
		arg.BiweeklyCount,
	)
	var i CurriculumItem
	err := row.Scan(
		&i.ID,
		&i.DisciplineID,
		&i.Kind,
		&i.TeacherID,
		&i.RoomType,
		&i.WeeklyCount,
		&i.BiweeklyCount,
	)
	return i, err
}
