// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActorType string

const (
	ActorTypeHuman   ActorType = "human"
	ActorTypeAiAgent ActorType = "ai_agent"
	ActorTypeSolver  ActorType = "solver"
)

func (e *ActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActorType(s)
	case string:
		*e = ActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActorType: %T", src)
	}
	return nil
}

type NullActorType struct {
	ActorType ActorType
	Valid     bool // Valid is true if ActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActorType) Scan(value interface{}) error {
	if value == nil {
		ns.ActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActorType), nil
}

func (e ActorType) Valid() bool {
	switch e {
	case ActorTypeHuman,
		ActorTypeAiAgent,
		ActorTypeSolver:
		return true
	}
	return false
}

func AllActorTypeValues() []ActorType {
	return []ActorType{
		ActorTypeHuman,
		ActorTypeAiAgent,
		ActorTypeSolver,
	}
}

type Availability string

const (
	AvailabilityUnavailable Availability = "unavailable"
	AvailabilityUndesired   Availability = "undesired"
	AvailabilityPreferred   Availability = "preferred"
)

func (e *Availability) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Availability(s)
	case string:
		*e = Availability(s)
	default:
		return fmt.Errorf("unsupported scan type for Availability: %T", src)
	}
	return nil
}

type NullAvailability struct {
	Availability Availability
	Valid        bool // Valid is true if Availability is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAvailability) Scan(value interface{}) error {
	if value == nil {
		ns.Availability, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Availability.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAvailability) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Availability), nil
}

func (e Availability) Valid() bool {
	switch e {
	case AvailabilityUnavailable,
		AvailabilityUndesired,
		AvailabilityPreferred:
		return true
	}
	return false
}

func AllAvailabilityValues() []Availability {
	return []Availability{
		AvailabilityUnavailable,
		AvailabilityUndesired,
		AvailabilityPreferred,
	}
}

type LessonKind string

const (
	LessonKindLecture LessonKind = "lecture"
	LessonKindSeminar LessonKind = "seminar"
	LessonKindLab     LessonKind = "lab"
)

func (e *LessonKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LessonKind(s)
	case string:
		*e = LessonKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LessonKind: %T", src)
	}
	return nil
}

type NullLessonKind struct {
	LessonKind LessonKind
	Valid      bool // Valid is true if LessonKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLessonKind) Scan(value interface{}) error {
	if value == nil {
		ns.LessonKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LessonKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLessonKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LessonKind), nil
}

func (e LessonKind) Valid() bool {
	switch e {
	case LessonKindLecture,
		LessonKindSeminar,
		LessonKindLab:
		return true
	}
	return false
}

func AllLessonKindValues() []LessonKind {
	return []LessonKind{
		LessonKindLecture,
		LessonKindSeminar,
		LessonKindLab,
	}
}

type Parity string

const (
	ParityEvery Parity = "every"
	ParityOdd   Parity = "odd"
	ParityEven  Parity = "even"
)

func (e *Parity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Parity(s)
	case string:
		*e = Parity(s)
	default:
		return fmt.Errorf("unsupported scan type for Parity: %T", src)
	}
	return nil
}

type NullParity struct {
	Parity Parity
	Valid  bool // Valid is true if Parity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParity) Scan(value interface{}) error {
	if value == nil {
		ns.Parity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Parity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Parity), nil
}

func (e Parity) Valid() bool {
	switch e {
	case ParityEvery,
		ParityOdd,
		ParityEven:
		return true
	}
	return false
}

func AllParityValues() []Parity {
	return []Parity{
		ParityEvery,
		ParityOdd,
		ParityEven,
	}
}

type Assignment struct {
	ScheduleID int64
	LessonID   int64
	Day        int16
	Period     int16
	Parity     Parity
	RoomID     pgtype.Int8
	Pinned     bool
	Cells      pgtype.Range[pgtype.Int4]
	TeacherID  int64
}

type AssignmentAudience struct {
	ScheduleID int64
	LessonID   int64
	GroupID    int64
	Division   string
	Part       int16
	Box        interface{}
	Cells      pgtype.Range[pgtype.Int4]
}

type AuditLog struct {
	ID           int64
	At           pgtype.Timestamptz
	ActorType    ActorType
	ActorID      string
	ViaAssistant bool
	Entity       string
	EntityID     string
	Before       []byte
	After        []byte
	Diff         []byte
	Reason       string
}

type Building struct {
	ID      int64
	Name    string
	Address string
}

type CurriculumAudience struct {
	CurriculumItemID int64
	GroupID          int64
	Division         string
	Part             int16
}

type CurriculumItem struct {
	ID            int64
	DisciplineID  int64
	Kind          LessonKind
	TeacherID     int64
	RoomType      string
	WeeklyCount   int16
	BiweeklyCount int16
}

type Discipline struct {
	ID   int64
	Name string
}

type Group struct {
	ID     int64
	Name   string
	Course int16
	Size   int32
}

type GroupDivision struct {
	GroupID  int64
	Division string
	Idx      int16
}

type Lesson struct {
	ID               int64
	CurriculumItemID int64
	Seq              int16
	Biweekly         bool
}

type Period struct {
	Number   int16
	StartsAt pgtype.Time
	EndsAt   pgtype.Time
}

type Room struct {
	ID         int64
	BuildingID int64
	Name       string
	RoomType   string
	Capacity   int32
}

type RoomAvailability struct {
	RoomID int64
	Day    int16
	Period int16
	Parity Parity
	Status Availability
}

type RoomType struct {
	Code string
	Name string
}

type Schedule struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Subgroup struct {
	ID       int64
	GroupID  int64
	Division string
	Part     int16
	Size     int32
}

type Teacher struct {
	ID        int64
	FullName  string
	ShortName string
}

type TeacherAvailability struct {
	TeacherID int64
	Day       int16
	Period    int16
	Parity    Parity
	Status    Availability
}

type TimeGrid struct {
	ID            bool
	Days          int16
	PeriodsPerDay int16
}
