// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddCurriculumAudience(ctx context.Context, arg AddCurriculumAudienceParams) error
	ClearCurriculumAudience(ctx context.Context, curriculumItemID int64) error
	ClearRoomAvailability(ctx context.Context, roomID int64) error
	ClearTeacherAvailability(ctx context.Context, teacherID int64) error
	CreateBuilding(ctx context.Context, arg CreateBuildingParams) (Building, error)
	CreateCurriculumItem(ctx context.Context, arg CreateCurriculumItemParams) (CurriculumItem, error)
	CreateDiscipline(ctx context.Context, name string) (Discipline, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateSchedule(ctx context.Context, name string) (Schedule, error)
	CreateSubgroup(ctx context.Context, arg CreateSubgroupParams) (Subgroup, error)
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error)
	DeleteAssignment(ctx context.Context, arg DeleteAssignmentParams) (int64, error)
	DeleteBuilding(ctx context.Context, id int64) (int64, error)
	DeleteCurriculumItem(ctx context.Context, id int64) (int64, error)
	DeleteDiscipline(ctx context.Context, id int64) (int64, error)
	DeleteGroup(ctx context.Context, id int64) (int64, error)
	DeleteLessonsOfItem(ctx context.Context, curriculumItemID int64) error
	DeleteRoom(ctx context.Context, id int64) (int64, error)
	DeleteSchedule(ctx context.Context, id int64) (int64, error)
	DeleteSubgroup(ctx context.Context, id int64) (int64, error)
	DeleteTeacher(ctx context.Context, id int64) (int64, error)
	GetBuilding(ctx context.Context, id int64) (Building, error)
	GetCurriculumItem(ctx context.Context, id int64) (CurriculumItem, error)
	GetDiscipline(ctx context.Context, id int64) (Discipline, error)
	GetGroup(ctx context.Context, id int64) (Group, error)
	GetRoom(ctx context.Context, id int64) (Room, error)
	GetSchedule(ctx context.Context, id int64) (Schedule, error)
	GetTeacher(ctx context.Context, id int64) (Teacher, error)
	GetTimeGrid(ctx context.Context) (TimeGrid, error)
	InsertAudit(ctx context.Context, arg InsertAuditParams) (AuditLog, error)
	ListAssignments(ctx context.Context, scheduleID int64) ([]Assignment, error)
	ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error)
	ListBuildings(ctx context.Context) ([]Building, error)
	ListCurriculumAudience(ctx context.Context) ([]CurriculumAudience, error)
	ListCurriculumItems(ctx context.Context) ([]CurriculumItem, error)
	ListDisciplines(ctx context.Context) ([]Discipline, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListLessons(ctx context.Context) ([]Lesson, error)
	ListPeriods(ctx context.Context) ([]Period, error)
	ListRoomAvailability(ctx context.Context) ([]RoomAvailability, error)
	ListRoomTypes(ctx context.Context) ([]RoomType, error)
	ListRooms(ctx context.Context) ([]Room, error)
	ListSchedules(ctx context.Context) ([]Schedule, error)
	ListSubgroups(ctx context.Context) ([]Subgroup, error)
	ListTeacherAvailability(ctx context.Context) ([]TeacherAvailability, error)
	ListTeachers(ctx context.Context) ([]Teacher, error)
	SetRoomAvailability(ctx context.Context, arg SetRoomAvailabilityParams) error
	SetTeacherAvailability(ctx context.Context, arg SetTeacherAvailabilityParams) error
	// Wipes reference data, curriculum, lessons and schedules (not the audit log) and restarts
	// identities. Used by the demo seed (cmd/seed) to reload its dataset idempotently.
	TruncateSeedData(ctx context.Context) error
	UpdateBuilding(ctx context.Context, arg UpdateBuildingParams) (Building, error)
	UpdateCurriculumItem(ctx context.Context, arg UpdateCurriculumItemParams) (CurriculumItem, error)
	UpdateDiscipline(ctx context.Context, arg UpdateDisciplineParams) (Discipline, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (Teacher, error)
	UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) error
	UpsertPeriod(ctx context.Context, arg UpsertPeriodParams) (Period, error)
	UpsertRoomType(ctx context.Context, arg UpsertRoomTypeParams) (RoomType, error)
	UpsertTimeGrid(ctx context.Context, arg UpsertTimeGridParams) (TimeGrid, error)
}

var _ Querier = (*Queries)(nil)
