// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRoomAvailability = `-- name: ClearRoomAvailability :exec
DELETE FROM room_availability WHERE room_id = $1
`

func (q *Queries) ClearRoomAvailability(ctx context.Context, roomID int64) error {
	_, err := q.db.Exec(ctx, clearRoomAvailability, roomID)
	return err
}

const clearTeacherAvailability = `-- name: ClearTeacherAvailability :exec
DELETE FROM teacher_availability WHERE teacher_id = $1
`

func (q *Queries) ClearTeacherAvailability(ctx context.Context, teacherID int64) error {
	_, err := q.db.Exec(ctx, clearTeacherAvailability, teacherID)
	return err
}

const createBuilding = `-- name: CreateBuilding :one
INSERT INTO buildings (name, address) VALUES ($1, $2) RETURNING id, name, address
`

type CreateBuildingParams struct {
	Name    string
	Address string
}

func (q *Queries) CreateBuilding(ctx context.Context, arg CreateBuildingParams) (Building, error) {
	row := q.db.QueryRow(ctx, createBuilding, arg.Name, arg.Address)
	var i Building
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}

const createDiscipline = `-- name: CreateDiscipline :one
INSERT INTO disciplines (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateDiscipline(ctx context.Context, name string) (Discipline, error) {
	row := q.db.QueryRow(ctx, createDiscipline, name)
	var i Discipline
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, course, size) VALUES ($1, $2, $3) RETURNING id, name, course, size
`

type CreateGroupParams struct {
	Name   string
	Course int16
	Size   int32
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.Course, arg.Size)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Course,
		&i.Size,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (building_id, name, room_type, capacity) VALUES ($1, $2, $3, $4) RETURNING id, building_id, name, room_type, capacity
`

type CreateRoomParams struct {
	BuildingID int64
	Name       string
	RoomType   string
	Capacity   int32
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.BuildingID,
		arg.Name,
		arg.RoomType,
		arg.Capacity,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.Name,
		&i.RoomType,
		&i.Capacity,
	)
	return i, err
}

const createSubgroup = `-- name: CreateSubgroup :one
INSERT INTO subgroups (group_id, division, part, size) VALUES ($1, $2, $3, $4) RETURNING id, group_id, division, part, size
`

type CreateSubgroupParams struct {
	GroupID  int64
	Division string
	Part     int16
	Size     int32
}

func (q *Queries) CreateSubgroup(ctx context.Context, arg CreateSubgroupParams) (Subgroup, error) {
	row := q.db.QueryRow(ctx, createSubgroup,
		arg.GroupID,
		arg.Division,
		arg.Part,
		arg.Size,
	)
	var i Subgroup
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Division,
		&i.Part,
		&i.Size,
	)
	return i, err
}

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO teachers (full_name, short_name) VALUES ($1, $2) RETURNING id, full_name, short_name
`

type CreateTeacherParams struct {
	FullName  string
	ShortName string
}

func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, createTeacher, arg.FullName, arg.ShortName)
	var i Teacher
	err := row.Scan(&i.ID, &i.FullName, &i.ShortName)
	return i, err
}

const deleteBuilding = `-- name: DeleteBuilding :execrows
DELETE FROM buildings WHERE id = $1
`

func (q *Queries) DeleteBuilding(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBuilding, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDiscipline = `-- name: DeleteDiscipline :execrows
DELETE FROM disciplines WHERE id = $1
`

func (q *Queries) DeleteDiscipline(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDiscipline, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRoom = `-- name: DeleteRoom :execrows
DELETE FROM rooms WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoom, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSubgroup = `-- name: DeleteSubgroup :execrows
DELETE FROM subgroups WHERE id = $1
`

func (q *Queries) DeleteSubgroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubgroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTeacher = `-- name: DeleteTeacher :execrows
DELETE FROM teachers WHERE id = $1
`

func (q *Queries) DeleteTeacher(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeacher, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBuilding = `-- name: GetBuilding :one
SELECT id, name, address FROM buildings WHERE id = $1
`

func (q *Queries) GetBuilding(ctx context.Context, id int64) (Building, error) {
	row := q.db.QueryRow(ctx, getBuilding, id)
	var i Building
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}

const getDiscipline = `-- name: GetDiscipline :one
SELECT id, name FROM disciplines WHERE id = $1
`

func (q *Queries) GetDiscipline(ctx context.Context, id int64) (Discipline, error) {
	row := q.db.QueryRow(ctx, getDiscipline, id)
	var i Discipline
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, course, size FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Course,
		&i.Size,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, building_id, name, room_type, capacity FROM rooms WHERE id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.Name,
		&i.RoomType,
		&i.Capacity,
	)
	return i, err
}

const getTeacher = `-- name: GetTeacher :one
SELECT id, full_name, short_name FROM teachers WHERE id = $1
`

func (q *Queries) GetTeacher(ctx context.Context, id int64) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacher, id)
	var i Teacher
	err := row.Scan(&i.ID, &i.FullName, &i.ShortName)
	return i, err
}

const getTimeGrid = `-- name: GetTimeGrid :one
SELECT id, days, periods_per_day FROM time_grid
`

func (q *Queries) GetTimeGrid(ctx context.Context) (TimeGrid, error) {
	row := q.db.QueryRow(ctx, getTimeGrid)
	var i TimeGrid
	err := row.Scan(&i.ID, &i.Days, &i.PeriodsPerDay)
	return i, err
}

const listBuildings = `-- name: ListBuildings :many
SELECT id, name, address FROM buildings ORDER BY name
`

func (q *Queries) ListBuildings(ctx context.Context) ([]Building, error) {
	rows, err := q.db.Query(ctx, listBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Building{}
	for rows.Next() {
		var i Building
		if err := rows.Scan(&i.ID, &i.Name, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisciplines = `-- name: ListDisciplines :many
SELECT id, name FROM disciplines ORDER BY name
`

func (q *Queries) ListDisciplines(ctx context.Context) ([]Discipline, error) {
	rows, err := q.db.Query(ctx, listDisciplines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Discipline{}
	for rows.Next() {
		var i Discipline
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, course, size FROM groups ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Course,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriods = `-- name: ListPeriods :many
SELECT number, starts_at, ends_at FROM periods ORDER BY number
`

func (q *Queries) ListPeriods(ctx context.Context) ([]Period, error) {
	rows, err := q.db.Query(ctx, listPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Period{}
	for rows.Next() {
		var i Period
		if err := rows.Scan(&i.Number, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomAvailability = `-- name: ListRoomAvailability :many
SELECT room_id, day, period, parity, status FROM room_availability ORDER BY room_id, day, period, parity
`

func (q *Queries) ListRoomAvailability(ctx context.Context) ([]RoomAvailability, error) {
	rows, err := q.db.Query(ctx, listRoomAvailability)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomAvailability{}
	for rows.Next() {
		var i RoomAvailability
		if err := rows.Scan(
			&i.RoomID,
			&i.Day,
			&i.Period,
			&i.Parity,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomTypes = `-- name: ListRoomTypes :many
SELECT code, name FROM room_types ORDER BY code
`

func (q *Queries) ListRoomTypes(ctx context.Context) ([]RoomType, error) {
	rows, err := q.db.Query(ctx, listRoomTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomType{}
	for rows.Next() {
		var i RoomType
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, building_id, name, room_type, capacity FROM rooms ORDER BY building_id, name
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.BuildingID,
			&i.Name,
			&i.RoomType,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubgroups = `-- name: ListSubgroups :many
SELECT id, group_id, division, part, size FROM subgroups ORDER BY group_id, division, part
`

func (q *Queries) ListSubgroups(ctx context.Context) ([]Subgroup, error) {
	rows, err := q.db.Query(ctx, listSubgroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subgroup{}
	for rows.Next() {
		var i Subgroup
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Division,
			&i.Part,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherAvailability = `-- name: ListTeacherAvailability :many
SELECT teacher_id, day, period, parity, status FROM teacher_availability ORDER BY teacher_id, day, period, parity
`

func (q *Queries) ListTeacherAvailability(ctx context.Context) ([]TeacherAvailability, error) {
	rows, err := q.db.Query(ctx, listTeacherAvailability)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherAvailability{}
	for rows.Next() {
		var i TeacherAvailability
		if err := rows.Scan(
			&i.TeacherID,
			&i.Day,
			&i.Period,
			&i.Parity,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachers = `-- name: ListTeachers :many
SELECT id, full_name, short_name FROM teachers ORDER BY full_name
`

func (q *Queries) ListTeachers(ctx context.Context) ([]Teacher, error) {
	rows, err := q.db.Query(ctx, listTeachers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Teacher{}
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(&i.ID, &i.FullName, &i.ShortName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoomAvailability = `-- name: SetRoomAvailability :exec
INSERT INTO room_availability (room_id, day, period, parity, status) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (room_id, day, period, parity) DO UPDATE SET status = EXCLUDED.status
`

type SetRoomAvailabilityParams struct {
	RoomID int64
	Day    int16
	Period int16
	Parity Parity
	Status Availability
}

func (q *Queries) SetRoomAvailability(ctx context.Context, arg SetRoomAvailabilityParams) error {
	_, err := q.db.Exec(ctx, setRoomAvailability,
		arg.RoomID,
		arg.Day,
		arg.Period,
		arg.Parity,
		arg.Status,
	)
	return err
}

const setTeacherAvailability = `-- name: SetTeacherAvailability :exec
INSERT INTO teacher_availability (teacher_id, day, period, parity, status) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (teacher_id, day, period, parity) DO UPDATE SET status = EXCLUDED.status
`

type SetTeacherAvailabilityParams struct {
	TeacherID int64
	Day       int16
	Period    int16
	Parity    Parity
	Status    Availability
}

func (q *Queries) SetTeacherAvailability(ctx context.Context, arg SetTeacherAvailabilityParams) error {
	_, err := q.db.Exec(ctx, setTeacherAvailability,
		arg.TeacherID,
		arg.Day,
		arg.Period,
		arg.Parity,
		arg.Status,
	)
	return err
}

const updateBuilding = `-- name: UpdateBuilding :one
UPDATE buildings SET name = $2, address = $3 WHERE id = $1 RETURNING id, name, address
`

type UpdateBuildingParams struct {
	ID      int64
	Name    string
	Address string
}

func (q *Queries) UpdateBuilding(ctx context.Context, arg UpdateBuildingParams) (Building, error) {
	row := q.db.QueryRow(ctx, updateBuilding, arg.ID, arg.Name, arg.Address)
	var i Building
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}

const updateDiscipline = `-- name: UpdateDiscipline :one
UPDATE disciplines SET name = $2 WHERE id = $1 RETURNING id, name
`

type UpdateDisciplineParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpdateDiscipline(ctx context.Context, arg UpdateDisciplineParams) (Discipline, error) {
	row := q.db.QueryRow(ctx, updateDiscipline, arg.ID, arg.Name)
	var i Discipline
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET name = $2, course = $3, size = $4 WHERE id = $1 RETURNING id, name, course, size
`

type UpdateGroupParams struct {
	ID     int64
	Name   string
	Course int16
	Size   int32
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Course,
		arg.Size,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Course,
		&i.Size,
	)
	return i, err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms SET building_id = $2, name = $3, room_type = $4, capacity = $5 WHERE id = $1 RETURNING id, building_id, name, room_type, capacity
`

type UpdateRoomParams struct {
	ID         int64
	BuildingID int64
	Name       string
	RoomType   string
	Capacity   int32
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.BuildingID,
		arg.Name,
		arg.RoomType,
		arg.Capacity,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.Name,
		&i.RoomType,
		&i.Capacity,
	)
	return i, err
}

const updateTeacher = `-- name: UpdateTeacher :one
UPDATE teachers SET full_name = $2, short_name = $3 WHERE id = $1 RETURNING id, full_name, short_name
`

type UpdateTeacherParams struct {
	ID        int64
	FullName  string
	ShortName string
}

func (q *Queries) UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, updateTeacher, arg.ID, arg.FullName, arg.ShortName)
	var i Teacher
	err := row.Scan(&i.ID, &i.FullName, &i.ShortName)
	return i, err
}

const upsertPeriod = `-- name: UpsertPeriod :one
INSERT INTO periods (number, starts_at, ends_at) VALUES ($1, $2, $3)
ON CONFLICT (number) DO UPDATE SET starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at
RETURNING number, starts_at, ends_at
`

type UpsertPeriodParams struct {
	Number   int16
	StartsAt pgtype.Time
	EndsAt   pgtype.Time
}

func (q *Queries) UpsertPeriod(ctx context.Context, arg UpsertPeriodParams) (Period, error) {
	row := q.db.QueryRow(ctx, upsertPeriod, arg.Number, arg.StartsAt, arg.EndsAt)
	var i Period
	err := row.Scan(&i.Number, &i.StartsAt, &i.EndsAt)
	return i, err
}

const upsertRoomType = `-- name: UpsertRoomType :one
INSERT INTO room_types (code, name) VALUES ($1, $2)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name
RETURNING code, name
`

type UpsertRoomTypeParams struct {
	Code string
	Name string
}

func (q *Queries) UpsertRoomType(ctx context.Context, arg UpsertRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRow(ctx, upsertRoomType, arg.Code, arg.Name)
	var i RoomType
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}

const upsertTimeGrid = `-- name: UpsertTimeGrid :one
INSERT INTO time_grid (id, days, periods_per_day) VALUES (true, $1, $2)
ON CONFLICT (id) DO UPDATE SET days = EXCLUDED.days, periods_per_day = EXCLUDED.periods_per_day
RETURNING id, days, periods_per_day
`

type UpsertTimeGridParams struct {
	Days          int16
	PeriodsPerDay int16
}

func (q *Queries) UpsertTimeGrid(ctx context.Context, arg UpsertTimeGridParams) (TimeGrid, error) {
	row := q.db.QueryRow(ctx, upsertTimeGrid, arg.Days, arg.PeriodsPerDay)
	var i TimeGrid
	err := row.Scan(&i.ID, &i.Days, &i.PeriodsPerDay)
	return i, err
}
