// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateSchedule(ctx context.Context, name string) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule, name)
	var i Schedule
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :execrows
DELETE FROM assignments WHERE schedule_id = $1 AND lesson_id = $2
`

type DeleteAssignmentParams struct {
	ScheduleID int64
	LessonID   int64
}

func (q *Queries) DeleteAssignment(ctx context.Context, arg DeleteAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssignment, arg.ScheduleID, arg.LessonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchedule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, name, created_at FROM schedules WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id int64) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listAssignments = `-- name: ListAssignments :many
SELECT schedule_id, lesson_id, day, period, parity, room_id, pinned, cells, teacher_id FROM assignments WHERE schedule_id = $1 ORDER BY lesson_id
`

func (q *Queries) ListAssignments(ctx context.Context, scheduleID int64) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssignments, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ScheduleID,
			&i.LessonID,
			&i.Day,
			&i.Period,
			&i.Parity,
			&i.RoomID,
			&i.Pinned,
			&i.Cells,
			&i.TeacherID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, name, created_at FROM schedules ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssignment = `-- name: UpsertAssignment :exec
INSERT INTO assignments (schedule_id, lesson_id, day, period, parity, room_id, pinned)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (schedule_id, lesson_id) DO UPDATE
SET day = EXCLUDED.day, period = EXCLUDED.period, parity = EXCLUDED.parity,
    room_id = EXCLUDED.room_id, pinned = EXCLUDED.pinned
`

type UpsertAssignmentParams struct {
	ScheduleID int64
	LessonID   int64
	Day        int16
	Period     int16
	Parity     Parity
	RoomID     pgtype.Int8
	Pinned     bool
}

func (q *Queries) UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) error {
	_, err := q.db.Exec(ctx, upsertAssignment,
		arg.ScheduleID,
		arg.LessonID,
		arg.Day,
		arg.Period,
		arg.Parity,
		arg.RoomID,
		arg.Pinned,
	)
	return err
}
