// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package db

import (
	"context"
)

const truncateSeedData = `-- name: TruncateSeedData :exec
TRUNCATE time_grid, periods, buildings, room_types, rooms, groups, subgroups, teachers,
    disciplines, teacher_availability, room_availability, curriculum_items, curriculum_audience,
    lessons, schedules, assignments
    RESTART IDENTITY CASCADE
`

// Wipes reference data, curriculum, lessons and schedules (not the audit log) and restarts
// identities. Used by the demo seed (cmd/seed) to reload its dataset idempotently.
func (q *Queries) TruncateSeedData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateSeedData)
	return err
}
